id: P005407
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD105837
  title: ཞིང་གྲོང་ཁྱིམ་ཚང་གི་འཚོ་བཅུད་དང་འཕྲོད་བསྟེན།
  author: ''
  volumes:
    314a81232bd44f009ead054188b36493:
      image_group_id: I1PD105839
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
